export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const INCREMENT = 'INCREMENT'
export const EDIT_DATE_FILTER = 'EDIT_DATE_FILTER'
export const EDIT_SELECT_FILTER = 'EDIT_SELECT_FILTER'

export const ADD_COMMENT = 'ADD_COMMENT'
export const LOAD_ARTICLE_COMMENTS = 'LOAD_ARTICLE_COMMENTS'

export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'

export const LOAD_ARTICLE = 'LOAD_ARTICLE'